apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: user-keycloak
  labels:
    app: user-keycloak
spec:
  instances: 1
  externalAccess:
    enabled: True
    host: keycloak.edgefarm.local
