site_name: EdgeFarm
theme:
  name: material
  palette:
    scheme: default
    accent: amber
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://edgefarmworkspace.slack.com
      name: Slack
    - icon: fontawesome/regular/envelope
      link: mailto:info@ci4rail.com
      name: Contact
  generator: false

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

repo_url: https://github.com/edgefarm/edgefarm
copyright: Copyright &copy; 2022 Ci4Rail GmbH

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark

nav:
  - Welcome:
      - Introduction: index.md
      - Use Cases: overview/usecases.md
      - System Overview: overview/system.md
      - Components: overview/components.md
  - Getting Started: gettingstarted/index.md
  - Knowledge Base:
      - Introduction: knowledge-base/index.md
      - How To's:
          - ... create a local test cluster: knowledge-base/howtos/create-local-cluster.md
          - ... join a physical edge node to the local test cluster: knowledge-base/howtos/join-a-physical-node-to-local-cluster.md
  - Reference:
      - edgefarm.core: reference/core.md
      - edgefarm.devices: reference/devices.md
      - edgefarm.applications: reference/applications.md
      - edgefarm.network: reference/network.md
      - edgefarm.monitor: reference/monitor.md
  #  - Best Practices: bestpractices/index.md
  - User How To's: userguide/index.md
  - Architecture:
      - Design Decissions: architecture/designdecissions.md
      - Overview: architecture/overview.md
      - edgefarm.core: architecture/edgefarm.core.md
      - edgefarm.devices: architecture/edgefarm.devices.md
      - edgefarm.applications: architecture/edgefarm.applications.md
      - edgefarm.network: architecture/edgefarm.network.md
      - edgefarm.monitor: architecture/edgefarm.monitor.md
