site_name: EdgeFarm - seamless edge computing
theme:
  name: material
  palette:
    - scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.collapsed
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://edgefarmworkspace.slack.com
      name: Slack
    - icon: fontawesome/regular/envelope
      link: mailto:info@ci4rail.com
      name: Contact
  generator: false

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

repo_url: https://github.com/edgefarm/edgefarm
copyright: Copyright &copy; 2023 Ci4Rail GmbH

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark

nav:
  - Welcome:
      - Introduction: index.md
      - Use Cases: overview/usecases.md
      - System Overview: overview/system.md
      - Components: overview/components.md
  - Knowledge Base:
      - Overview: knowledge-base/index.md
      - Getting Started:
          - Overview: knowledge-base/gettingstarted/index.md
          - Example Application: knowledge-base/gettingstarted/example-application.md
          - Portal: knowledge-base/gettingstarted/portal.md
      - Concepts:
          - Overview: knowledge-base/concepts/index.md
          - Design Decissions: knowledge-base/concepts/designdecissions.md
          - Concepts:
              - edgefarm.core: knowledge-base/concepts/edgefarm.core.md
              - edgefarm.applications: knowledge-base/concepts/edgefarm.applications.md
              - edgefarm.network: knowledge-base/concepts/edgefarm.network.md
              - edgefarm.monitor: knowledge-base/concepts/edgefarm.monitor.md
      - Tutorials:
          # - Overview: knowledge-base/tutorials/index.md
          - Cluster:
              - Create a local test cluster: knowledge-base/tutorials/cluster/create-local-cluster.md
              - Join a Ubuntu 22.04 edge node to the local test cluster: knowledge-base/tutorials/cluster/join-ubuntu-22-04-edge-node.md
          - Learn EdgeFarm Basics:
              - Deploy an App: knowledge-base/tutorials/edgefarm-basics/deploy-an-app.md
              # - Deploy an Network: knowledge-base/tutorials/edgefarm-basics/deploy-a-network.md
              # - Deploy an App with Network: knowledge-base/tutorials/edgefarm-basics/deploy-an-app-with-network.md
              # - Access Network from outside the cluster: knowledge-base/tutorials/edgefarm-basics/access-network-from-outside-the-cluster.md
      - Reference:
          - Overview: knowledge-base/reference/index.md
          - Glossary: knowledge-base/reference/reference/glossary.md
          - EdgeFarm API:
              - API Overview: knowledge-base/reference/reference/api.md
              - edgefarm.applications:
                  - Overview: knowledge-base/reference/reference/api/applications/overview.md
                  - Application Spec: knowledge-base/reference/reference/api/applications/application-spec.md
                  - Network Trait Spec: knowledge-base/reference/reference/api/applications/network-trait-spec.md
                  - Storage Trait Spec: knowledge-base/reference/reference/api/applications/storage-trait-spec.md
                  - Examples: knowledge-base/reference/reference/api/applications/examples.md
              - edgefarm.network:
                  - Overview: knowledge-base/reference/reference/api/network/overview.md
                  - Spec: knowledge-base/reference/reference/api/network/spec.md
                  - Examples: knowledge-base/reference/reference/api/network/examples.md
          - Well-Known Labels, Annotations and Taints: knowledge-base/reference/well-known/well-known.md
  - Pricing: pricing/index.md
  #  - Best Practices: bestpractices/index.md
