apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-namespace-name

secretGenerator:
- name: example-secret
  type: Opaque
  env: ./secrets.env
  files:
  - ./secret.file
generatorOptions:
 disableNameSuffixHash: true
