version: v2beta1
name: example-consumer

deployments:
  example-consumer:
    kubectl:
      manifests:
        - deploy/**/

pipelines:
  deploy: |-
    #!/bin/bash
    set -e
    create_deployments example-consumer

dev:
  example-consumer:
    labelSelector:
      app.kubernetes.io/instance: example-consumer
    devImage: ghcr.io/edgefarm/edgefarm/example-basic-consumer:latest
    namespace: default
    terminal: {}
    ports:
      - port: "2345"
      - port: "5006"
    sync:
      - path: ./../../:/app
        excludePaths:
          - .git
    patches:
      - op: remove
        path: spec.securityContext
      - op: remove
        path: spec.containers[0].resources
