apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  {{- with .Values.cloudHub.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 10000
    name: wss
    targetPort: 20000
  - port: 10002
    name: https
    targetPort: 20002
  - port: 10003
    name: stream
    targetPort: 20003
  - port: 10004
    name: tunnel
    targetPort: 20004
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: LoadBalancer
