name: publish-docs
on:
  push:
    branches:
      - beta
    paths:
      - "docs/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-glightbox
      - run: mkdocs gh-deploy --force
