name: release

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    types:
      - completed
    branches:
      - main
      - beta

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
        run: |-
          #!/bin/bash
          set -e
          # add more plugins: https://semantic-release.gitbook.io/semantic-release/extending/plugins-list
          npm install @semantic-release/exec @semantic-release/git -D
          npx -c semantic-release
