name: release-kind-image

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    types:
      - completed
    paths:
      - "build/kind/Dockerfile"
    branches:
      - main
      - beta

env:
  REGISTRY: ghcr.io
  KIND_NODE_VERSION: v1.22.7

jobs:
  release-kind-image:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build/kind
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/edgefarm/edgefarm/kind-node:${{ env.KIND_NODE_VERSION }}
          build-args: |
            VERSION=${{ env.KIND_NODE_VERSION }}
