name: release-kind-image

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    types:
      - completed
    branches:
      - main
      - beta

env:
  REGISTRY: ghcr.io
  K8S_VERSION: v1.22.7
  KIND_NODE_VERSION: v1.22.7-systemd

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: commitlint.yml
          name: original-refs
          workflow_conclusion: success

      - name: set REF_BASE to env
        run: |
          echo "BASE=$(cat base.txt)" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=$(cat current-branch.txt)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ env.BASE }}
          ref: ${{ env.CURRENT_BRANCH }}
          filters: |
            dockerfile:
              - 'build/kind/Dockerfile'

  release-kind-image:
    needs: check_paths
    if: needs.check_paths.outputs.dockerfile_changed == 'true'
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: build/kind
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/edgefarm/edgefarm/kind-node:${{ env.KIND_NODE_VERSION }}
          build-args: |
            VERSION=${{ env.K8S_VERSION }}
